name: WMPS3
slug: wmps3
version: "0.4.0"
description: Cashless laundry payment system (WMPS) — simulate & per-machine toggles with ADAM-6050 and HA-keypad support
url: https://example.com/wmps3
arch: [aarch64, amd64, armhf, armv7, i386]

startup: services
init: false
homeassistant_api: true

# Permissions
apparmor: false
full_access: true
# privileged:
#   - SYS_ADMIN
#   - SYS_RAWIO

ingress: true
ingress_port: 8000
ingress_stream: true

map:
  - share:rw
  - config:rw

devices:
  - /dev/input:/dev/input:rwm
  - /dev/bus/usb:/dev/bus/usb:rwm
udev: true

options:
  ha_url: "http://supervisor/core"
  ha_ws_url: "ws://supervisor/core/websocket"
  ha_token: ""

  # Keypad / TTS
  keypad_source: "evdev"
  keypad_device: "/dev/input/by-id/usb-SIGMACHIP_USB_Keyboard-event-kbd"
  ha_event_type: "keyboard_remote_command_received"
  confirm_keys: [28, 96]            # Enter (28), Keypad Enter (96)
  tts_entity_id: "tts.google_translate_en_com"
  tts_language: "en"
  tts_service: "google_translate_say"  # legacy fallback service
  media_player: "media_player.vlc_telnet"

  # ADAM & run-mode
  adam_host: "192.168.1.101"
  adam_port: 502
  adam_unit_id: 1
  do_mode: "pulse"
  pulse_seconds: 0.8
  invert_di: false
  activation_confirm_timeout_s: 15

  simulate: false

  # Defaults & pricing
  washing_minutes: 30
  dryer_minutes: 60
  price_washing: 5.0
  price_dryer: 5.0

  # Security
  security:
    code_entry_timeout_s: 30
    max_failed_attempts: 5
    lockout_seconds: 120

  # Per-machine enable toggles
  machine_1_enabled: true
  machine_2_enabled: true
  machine_3_enabled: true
  machine_4_enabled: true
  machine_5_enabled: true
  machine_6_enabled: true

  # Machine map
  machines:
    - id: 1
      enabled: true
      label: "Washing Machine 1"
      cycle_minutes: 30
      price: 5.0
      ha_switch: "switch.washer_1_control"
      ha_sensor: "binary_sensor.washer_1_status"
      relay: 0
      di: 0
      do_mode: pulse
    - id: 2
      enabled: true
      label: "Washing Machine 2"
      cycle_minutes: 30
      price: 5.0
      ha_switch: "switch.washer_2_control"
      ha_sensor: "binary_sensor.washer_2_status"
      relay: 1
      di: 1
      do_mode: pulse
    - id: 3
      enabled: true
      label: "Washing Machine 3"
      cycle_minutes: 30
      price: 5.0
      ha_switch: "switch.washer_3_control"
      ha_sensor: "binary_sensor.washer_3_status"
      relay: 2
      di: 2
      do_mode: pulse
    - id: 4
      enabled: true
      label: "Dryer 1"
      cycle_minutes: 60
      price: 5.0
      ha_switch: "switch.dryer_4_control"
      ha_sensor: "binary_sensor.dryer_4_status"
      relay: 3
      di: 3
      do_mode: pulse
    - id: 5
      enabled: true
      label: "Dryer 2"
      cycle_minutes: 60
      price: 5.0
      ha_switch: "switch.dryer_5_control"
      ha_sensor: "binary_sensor.dryer_5_status"
      relay: 4
      di: 4
      do_mode: pulse
    - id: 6
      enabled: true
      label: "Dryer 3"
      cycle_minutes: 60
      price: 5.0
      ha_switch: "switch.dryer_6_control"
      ha_sensor: "binary_sensor.dryer_6_status"
      relay: 5
      di: 5
      do_mode: pulse

schema:
  ha_url: str
  ha_ws_url: str?
  ha_token: password?

  keypad_source: list(ha|evdev|auto)?
  keypad_device: str?
  ha_event_type: str?
  confirm_keys: list(int)?

  tts_entity_id: str?
  tts_language: str?
  tts_service: str?
  media_player: str?

  adam_host: str?
  adam_port: int?
  adam_unit_id: int?
  do_mode: list(pulse|hold)?
  pulse_seconds: float?
  invert_di: bool?
  activation_confirm_timeout_s: int

  simulate: bool

  washing_minutes: int
  dryer_minutes: int
  price_washing: float
  price_dryer: float

  security:
    code_entry_timeout_s: int
    max_failed_attempts: int
    lockout_seconds: int

  machine_1_enabled: bool
  machine_2_enabled: bool
  machine_3_enabled: bool
  machine_4_enabled: bool
  machine_5_enabled: bool
  machine_6_enabled: bool

  machines:
    - id: int
      enabled: bool
      label: str?
      cycle_minutes: int?
      price: float?
      ha_switch: str?
      ha_sensor: str?
      relay: int?
      di: int?
      do_mode: list(pulse|hold)?
