ha_url: http://192.168.1.72:8123
ha_ws_url: ws://192.168.1.72:8123/api/websocket
ha_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZDg3YWY2MTZkOGQ0ZDM1OTZiM2NlZGJmYzNlZDk4YyIsImlhdCI6MTc1NzIzNDc1NSwiZXhwIjoyMDcyNTk0NzU1fQ.qygl9SkMZ-RY4bFIzQvIsxWIoVmhBCULMEcYz1jWvVQ"

keypad_source: ha
ha_event_type: keyboard_remote_command_received
confirm_keys:
  - 28
  - 96

tts_service: tts.google_translate_speak
media_player: media_player.vlc_telnet

adam_host: 192.168.1.101
adam_port: 502
adam_unit_id: 1
do_mode: pulse
pulse_seconds: 0.8
invert_di: false
activation_confirm_timeout_s: 15

simulate: false
washing_minutes: 30
dryer_minutes: 60
price_washing: 5.0
price_dryer: 5.0

security:
  code_entry_timeout_s: 30
  max_failed_attempts: 5
  lockout_seconds: 120

machine_1_enabled: true
machine_2_enabled: true
machine_3_enabled: true
machine_4_enabled: true
machine_5_enabled: true
machine_6_enabled: true

machines:
  - id: 1
    enabled: true
    label: "Washing Machine 1"
    cycle_minutes: 30
    price: 5.0
    ha_switch: switch.washer_1_control
    ha_sensor: binary_sensor.washer_1_status
    relay: 0
    di: 0
    do_mode: pulse
  - id: 2
    enabled: true
    label: "Washing Machine 2"
    cycle_minutes: 30
    price: 5.0
    ha_switch: switch.washer_2_control
    ha_sensor: binary_sensor.washer_2_status
    relay: 1
    di: 1
    do_mode: pulse
  - id: 3
    enabled: true
    label: "Washing Machine 3"
    cycle_minutes: 30
    price: 5.0
    ha_switch: switch.washer_3_control
    ha_sensor: binary_sensor.washer_3_status
    relay: 2
    di: 2
    do_mode: pulse
  - id: 4
    enabled: true
    label: "Dryer 1"
    cycle_minutes: 60
    price: 5.0
    ha_switch: switch.dryer_4_control
    ha_sensor: binary_sensor.dryer_4_status
    relay: 3
    di: 3
    do_mode: pulse
  - id: 5
    enabled: true
    label: "Dryer 2"
    cycle_minutes: 60
    price: 5.0
    ha_switch: switch.dryer_5_control
    ha_sensor: binary_sensor.dryer_5_status
    relay: 4
    di: 4
    do_mode: pulse
  - id: 6
    enabled: true
    label: "Dryer 3"
    cycle_minutes: 60
    price: 5.0
    ha_switch: switch.dryer_6_control
    ha_sensor: binary_sensor.dryer_6_status
    relay: 5
    di: 5
    do_mode: pulse
