name: WMPS
slug: wmps
version: "0.1.0"
description: Cashless laundry payment system (WMPS)
arch:
  - aarch64
  - amd64
startup: services
init: false

# Ingress UI
ingress: true
ingress_port: 8000
ingress_stream: true

# NOTE: Do NOT set 'ports' or 'webui' when using Ingress.

options:
  ha_url: "http://supervisor/core"
  ha_token: ""
  tts_service: "speak"
  media_player: "media_player.vlc_telnet"
  adam_host: "192.168.1.101"
  adam_port: 502
  simulate: false
  price_per_cycle: 30
  machines:
    - id: 1
      relay: 0
    - id: 2
      relay: 1

schema:
  ha_url: str
  ha_token: password
  tts_service: str
  media_player: str
  adam_host: str
  adam_port: int
  simulate: bool
  price_per_cycle: int
  machines:
    - id: int
      relay: int
