name: WMPS
slug: wmps
version: "0.3.0"
description: Cashless laundry payment system (WMPS) — ADAM-6050 + HA keypad + VLC TTS
url: https://example.com/wmps
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: services
init: false

# Ingress UI
ingress: true
ingress_port: 8000
ingress_stream: true
# Do NOT set 'ports' or 'webui' when using Ingress.

# Shared storage (mirrors go under /share/wmps)
map:
  - share:rw

# USB keypad access from the add-on container
devices:
  - /dev/input:/dev/input:rwm
udev: true

options:
  # Home Assistant API (inside HA OS use supervisor/core)
  ha_url: "http://supervisor/core"
  ha_token: ""
  tts_service: "tts.google_translate_say"
  media_player: "media_player.vlc_telnet"

  # Keypad source: "ha" (WebSocket events), "evdev" (USB), or "auto"
  keypad_source: "ha"
  ha_ws_url: null
  ha_event_type: "keyboard_remote_command_received"

  # ADAM-6050 (set host to enable direct DO/DI; otherwise HA entities are used)
  adam_host: "192.168.1.101"
  adam_port: 502
  adam_unit_id: 1
  do_mode: "pulse"        # "pulse" or "hold"
  pulse_seconds: 0.8
  invert_di: false

  # Safe default: start in simulate mode (no hardware writes)
  simulate: true

  # Defaults by machine category
  washing_minutes: 30
  dryer_minutes: 60
  price_washing: 5.0
  price_dryer: 5.0

  # DI confirmation timeout after activation (seconds)
  activation_confirm_timeout_s: 15

  # Keypad security/lock settings
  security:
    code_entry_timeout_s: 30
    max_failed_attempts: 5
    lockout_seconds: 120

  # Top-level enable/disable flags
  machine_1_enabled: true
  machine_2_enabled: true
  machine_3_enabled: true
  machine_4_enabled: true
  machine_5_enabled: true
  machine_6_enabled: true

  # Machine mapping — prefer HA entities; optionally add ADAM relay/di indexes
  machines:
    - id: 1
      enabled: true
      ha_switch: switch.washer_1_control
      ha_sensor: binary_sensor.washer_1_status
      relay: 0
      di: 0
    - id: 2
      enabled: true
      ha_switch: switch.washer_2_control
      ha_sensor: binary_sensor.washer_2_status
      relay: 1
      di: 1
    - id: 3
      enabled: true
      ha_switch: switch.washer_3_control
      ha_sensor: binary_sensor.washer_3_status
      relay: 2
      di: 2
    - id: 4
      enabled: true
      ha_switch: switch.dryer_4_control
      ha_sensor: binary_sensor.dryer_4_status
      relay: 3
      di: 3
    - id: 5
      enabled: true
      ha_switch: switch.dryer_5_control
      ha_sensor: binary_sensor.dryer_5_status
      relay: 4
      di: 4
    - id: 6
      enabled: true
      ha_switch: switch.dryer_6_control
      ha_sensor: binary_sensor.dryer_6_status
      relay: 5
      di: 5

schema:
  ha_url: str
  ha_token: password
  tts_service: str?
  media_player: str?

  keypad_source: str?
  ha_ws_url: str?
  ha_event_type: str?

  adam_host: str?
  adam_port: int?
  adam_unit_id: int?
  do_mode: str?
  pulse_seconds: float?
  invert_di: bool?

  simulate: bool

  washing_minutes: int
  dryer_minutes: int
  price_washing: float
  price_dryer: float

  activation_confirm_timeout_s: int

  security:
    code_entry_timeout_s: int
    max_failed_attempts: int
    lockout_seconds: int

  machine_1_enabled: bool
  machine_2_enabled: bool
  machine_3_enabled: bool
  machine_4_enabled: bool
  machine_5_enabled: bool
  machine_6_enabled: bool

  machines:
    - id: int
      enabled: bool
      ha_switch: str?
      ha_sensor: str?
      relay: int?
      di: int?
